In [1]:
import numpy as np 

In [3]:
array1=np.array([10,12,13.14])
array1

array([10.  , 12.  , 13.14])

In [4]:
type(array1)

numpy.ndarray

In [5]:
n1=np.array([[1,2,3,4],[4,5,6,7]])
n1

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [8]:
n3=np.zeros((1,2))
n3

array([[0., 0.]])

In [9]:
n4=np.zeros((4,5))
n4

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
n5=np.full((2,5),10)
n5

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [11]:
n6=np.arange(10,20)
n6

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [13]:
n7=np.arange(10,20,3)
n7

array([10, 13, 16, 19])

In [15]:
n8=np.random.randint(1,15,6)
n8

array([14,  9,  8, 14,  3,  1])

In [16]:
n5.shape

(2, 5)

In [17]:
n5.shape=(5,2)

In [18]:
n5

array([[10, 10],
       [10, 10],
       [10, 10],
       [10, 10],
       [10, 10]])

In [19]:
ar1=np.array([10,20,30,40])
ar2=np.array([11,12,1,3,14])

## Joining Numpy arrays