## Introduction to Scikit-Learn

In [55]:
import pandas as pd 

In [56]:
heart_diss=pd.read_csv("heart-disease.csv")
heart_diss

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [57]:
X= heart_diss.drop("target",axis=1)
Y=heart_diss["target"]

In [58]:
from sklearn.ensemble import RandomForestClassifier
clf= RandomForestClassifier(n_estimators=100)
clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [59]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.2)

In [60]:
clf.fit(x_train,y_train);

In [61]:
clf.score(x_train,y_train)

1.0

In [62]:
clf.score(x_test,y_test)

0.8032786885245902

In [63]:
y_preds=clf.predict(x_test)
y_preds

array([1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [64]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
print(classification_report(y_test,y_preds))

              precision    recall  f1-score   support

           0       0.83      0.71      0.77        28
           1       0.78      0.88      0.83        33

    accuracy                           0.80        61
   macro avg       0.81      0.80      0.80        61
weighted avg       0.81      0.80      0.80        61



In [65]:
print(confusion_matrix(y_test,y_preds))

[[20  8]
 [ 4 29]]


In [66]:
print(accuracy_score(y_test,y_preds))

0.8032786885245902


In [67]:
import numpy as np 
np.random.seed(42)

for i in range (10,110,10):
    clf=RandomForestClassifier(n_estimators=i)
    clf.fit(x_train,y_train)
    print(f"Model Accuracy on n estimators{i}: {clf.score(x_test,y_test)*100:.2f}%")
    print("")

Model Accuracy on n estimators10: 77.05%

Model Accuracy on n estimators20: 78.69%

Model Accuracy on n estimators30: 80.33%

Model Accuracy on n estimators40: 83.61%

Model Accuracy on n estimators50: 81.97%

Model Accuracy on n estimators60: 80.33%

Model Accuracy on n estimators70: 75.41%

Model Accuracy on n estimators80: 77.05%

Model Accuracy on n estimators90: 80.33%

Model Accuracy on n estimators100: 80.33%



In [68]:
import pickle
pickle.dump(clf,open("RandimForestClassifier.pkl","wb"))

In [69]:
loaded_model=pickle.load(open("RandimForestClassifier.pkl","rb"))
loaded_model.score(x_test,y_test)

0.8032786885245902

## CAR SALES MODEL 
#### Converting the string into integer so that machine learnong model can easily work 

In [70]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [71]:
data=pd.read_csv("car-sales-extended.csv")
# data.head()
len(data)
data.head()

Make Colour  Odometer (KM)  Doors  Price
0   Honda  White          35431      4  15323
1     BMW   Blue         192714      5  19943
2   Honda  White          84714      4  28343
3  Toyota  White         154365      4  13434
4  Nissan   Blue         181577      3  14043

In [72]:
X=data.drop("Price", axis=1)
Y=data["Price"]

In [73]:
from sklearn.model_selection import train_test_split
X_train ,X_test, y_train, y_test= train_test_split(X,Y,test_size=0.2)


In [74]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features=["Make","Colour","Doors"]
one_hot=OneHotEncoder()
transformer=ColumnTransformer([("one_hot",
                                 one_hot,
                                 categorical_features,
                               )],
                              remainder="passthrough")
transformed_X=transformer.fit(X)
transformed_X

ColumnTransformer(remainder='passthrough',
                  transformers=[('one_hot', OneHotEncoder(),
                                 ['Make', 'Colour', 'Doors'])])

In [75]:
import sklearn
print(sklearn.__version__)

1.2.2


## Fill the empty Values using Pandas

In [76]:
data_missing=pd.read_csv("car-sales-extended-missing-data.csv")
data.head()

Make Colour  Odometer (KM)  Doors  Price
0   Honda  White          35431      4  15323
1     BMW   Blue         192714      5  19943
2   Honda  White          84714      4  28343
3  Toyota  White         154365      4  13434
4  Nissan   Blue         181577      3  14043

In [77]:
len(data_missing)

1000

In [78]:
data_missing.isna().sum()

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

In [79]:
X=data_missing.drop("Price", axis=1)
Y=data_missing["Price"]

In [80]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_elements=["Make","Colour","Doors"]
one_hot=OneHotEncoder()
transformer=ColumnTransformer([("one_hot",
                               one_hot,
                               categorical_elements)],
                             remainder="passthrough")
transformed_X=transformer.fit(data_missing)
transformed_X

ColumnTransformer(remainder='passthrough',
                  transformers=[('one_hot', OneHotEncoder(),
                                 ['Make', 'Colour', 'Doors'])])

In [81]:
data_missing.isna().sum()

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

#### Fill the Missing Values 

In [82]:
data_missing["Make"].fillna("missing",inplace=True)
data_missing["Colour"].fillna("missing",inplace=True)
data_missing["Doors"].fillna(4,inplace=True)
data_missing["Odometer (KM)"].fillna(data_missing["Odometer (KM)"].mean(),inplace=True)

In [83]:
data_missing

Make Colour  Odometer (KM)  Doors    Price
0      Honda  White        35431.0    4.0  15323.0
1        BMW   Blue       192714.0    5.0  19943.0
2      Honda  White        84714.0    4.0  28343.0
3     Toyota  White       154365.0    4.0  13434.0
4     Nissan   Blue       181577.0    3.0  14043.0
..       ...    ...            ...    ...      ...
995   Toyota  Black        35820.0    4.0  32042.0
996  missing  White       155144.0    3.0   5716.0
997   Nissan   Blue        66604.0    4.0  31570.0
998    Honda  White       215883.0    4.0   4001.0
999   Toyota   Blue       248360.0    4.0  12732.0

[1000 rows x 5 columns]

In [84]:
len(data_missing)

1000

In [85]:
data_missing.isna().sum()

Make              0
Colour            0
Odometer (KM)     0
Doors             0
Price            50
dtype: int64

In [86]:
X=data_missing.drop("Price",axis=1)
Y=data_missing["Price"]

In [87]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_elements=["Make","Colour","Doors"]
one_hot=OneHotEncoder()
transformer=ColumnTransformer([("one_hot",
                               one_hot,
                               categorical_elements)],
                             remainder="passthrough")
transformed_X=transformer.fit(data_missing)
transformed_X

ColumnTransformer(remainder='passthrough',
                  transformers=[('one_hot', OneHotEncoder(),
                                 ['Make', 'Colour', 'Doors'])])

In [88]:
# from sklearn.model_selection import train_test_split
# X_train,X_test,Y_train,Y_test=train_test_split(transformed_X,Y,test_size=0.3)

# from sklearn.ensemble import RandomForestRegressor
# model=RandomForestRegressor()
# model.fit(X_train,Y_train)
# model.score(X_test,Y_test)

## Fill the missing values with the sklearn

In [89]:
data_set=pd.read_csv("car-sales-extended-missing-data.csv")
data_set

Make Colour  Odometer (KM)  Doors    Price
0     Honda  White        35431.0    4.0  15323.0
1       BMW   Blue       192714.0    5.0  19943.0
2     Honda  White        84714.0    4.0  28343.0
3    Toyota  White       154365.0    4.0  13434.0
4    Nissan   Blue       181577.0    3.0  14043.0
..      ...    ...            ...    ...      ...
995  Toyota  Black        35820.0    4.0  32042.0
996     NaN  White       155144.0    3.0   5716.0
997  Nissan   Blue        66604.0    4.0  31570.0
998   Honda  White       215883.0    4.0   4001.0
999  Toyota   Blue       248360.0    4.0  12732.0

[1000 rows x 5 columns]

In [90]:
data_set.isna().sum()

data_set.dropna(subset="Price",inplace=True)
data_set.isna().sum()

Make             47
Colour           46
Odometer (KM)    48
Doors            47
Price             0
dtype: int64

In [91]:
X=data_set.drop("Price",axis=1)
Y=data_set["Price"]

from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2)

In [92]:
# importing sklearn imputer module 
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

#fill the categaorical values with numerical and missing values
cat_imputer=SimpleImputer(strategy="constant",fill_value="missing")
door_imputer=SimpleImputer(strategy="constant",fill_value=4)
num_imputer=SimpleImputer(strategy='mean')

cat_feature=["Make","Colour"]
door_feature=["Doors"]
num_feature=["Odometer (KM)"]

imputer=ColumnTransformer([
    ("cat_imputer",cat_imputer,cat_feature,),
    ("door_imputer",door_imputer,door_feature),
    ("num_imputer",num_imputer,num_feature)
])

fit_X_train=imputer.fit_transform(X_train)
fit_X_test=imputer.fit_transform(X_test)

fit_X_train
fit_X_test

array([['Honda', 'missing', 4.0, 133230.76923076922],
       ['Toyota', 'Green', 4.0, 44436.0],
       ['Honda', 'Green', 4.0, 46085.0],
       ['Toyota', 'Blue', 4.0, 207048.0],
       ['Honda', 'White', 4.0, 85975.0],
       ['BMW', 'White', 5.0, 192673.0],
       ['Toyota', 'Red', 4.0, 190211.0],
       ['Nissan', 'Black', 4.0, 239908.0],
       ['Honda', 'White', 4.0, 187380.0],
       ['Toyota', 'Blue', 4.0, 223390.0],
       ['Nissan', 'Green', 4.0, 229929.0],
       ['missing', 'Green', 4.0, 133230.76923076922],
       ['Honda', 'White', 4.0, 56534.0],
       ['Toyota', 'White', 4.0, 244404.0],
       ['Honda', 'Red', 4.0, 61504.0],
       ['Toyota', 'Black', 4.0, 144944.0],
       ['Honda', 'missing', 4.0, 42379.0],
       ['Nissan', 'Blue', 4.0, 71527.0],
       ['Honda', 'Blue', 4.0, 190532.0],
       ['Honda', 'Black', 4.0, 123924.0],
       ['Toyota', 'White', 4.0, 112004.0],
       ['Honda', 'White', 4.0, 195787.0],
       ['Toyota', 'Blue', 4.0, 135080.0],
       ['Toyota

In [93]:
filled_X_tarin_df=pd.DataFrame(fit_X_train,columns=["Make","Colour","Doors","Odometer (KM)"])
filled_X_tarin_df

filled_X_test_df=pd.DataFrame(fit_X_test,columns=["Make","Colour","Doors","Odometer (KM)"])

In [94]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_value=["Make","Colour","Doors"]
one_hot=OneHotEncoder()
transformer=ColumnTransformer([
                    ("one_hot",one_hot,categorical_value)],
                    remainder="passthrough")
transformed_X_train=transformer.fit_transform(filled_X_tarin_df)
trasnformed_X_test=transformer.fit_transform(filled_X_test_df)

transformed_X_train.toarray()


array([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        1.00000000e+00, 0.00000000e+00, 7.33600000e+04],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        1.00000000e+00, 0.00000000e+00, 1.99985000e+05],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        1.00000000e+00, 0.00000000e+00, 1.30420386e+05],
       ...,
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        1.00000000e+00, 0.00000000e+00, 6.92220000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 1.91024000e+05],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 1.10490000e+04]])

In [95]:
np.random.seed(42)
from sklearn.ensemble import RandomForestRegressor
for i in range (10,110,10):
    model=RandomForestRegressor(n_estimators=i)
    model.fit(transformed_X_train,Y_train)
    print(f"sCORE FOR ESTIMATOR {i} is :{model.score(trasnformed_X_test,Y_test)*100:.2f}")
    

sCORE FOR ESTIMATOR 10 is :29.76
sCORE FOR ESTIMATOR 20 is :27.45
sCORE FOR ESTIMATOR 30 is :29.64
sCORE FOR ESTIMATOR 40 is :30.55
sCORE FOR ESTIMATOR 50 is :31.34
sCORE FOR ESTIMATOR 60 is :29.63
sCORE FOR ESTIMATOR 70 is :31.81
sCORE FOR ESTIMATOR 80 is :29.64
sCORE FOR ESTIMATOR 90 is :29.98
sCORE FOR ESTIMATOR 100 is :29.75


## Choosing the right model for the dataset


In [96]:
from sklearn.datasets import fetch_california_housing
housing= fetch_california_housing()
housing

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
           37.88      , -122.23      ],
        [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
           37.86      , -122.22      ],
        [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
           37.85      , -122.24      ],
        ...,
        [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
           39.43      , -121.22      ],
        [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
           39.43      , -121.32      ],
        [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
           39.37      , -121.24      ]]),
 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894]),
 'frame': None,
 'target_names': ['MedHouseVal'],
 'feature_names': ['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'],
 'DESCR': '.. _california_housing_dataset:\n

In [97]:
housing_data=pd.DataFrame(housing["data"],columns=housing["feature_names"])
housing_data

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   
...       ...       ...       ...        ...         ...       ...       ...   
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48   
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49   
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43   
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43   
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37   

       Longitude  
0        -122.23  
1        -122.22  
2        -122.24  
3        -122.25  
4        -122.25  
...          ...  
20635    -121.09  
20636    -121.21  
20637    -121.22  
20638    -121.32  
20639    -121.24  

[20640 rows x 8 columns]

In [98]:
housing_data["target"]=housing["target"]
housing_data.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  target  
0    -122.23   4.526  
1    -122.22   3.585  
2    -122.24   3.521  
3    -122.25   3.413  
4    -122.25   3.422

In [99]:
## Choosig the right model 
np.random.seed(42)

X=housing_data.drop("target",axis=1)
Y=housing_data["target"]

from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.2)

from sklearn.linear_model import Ridge
for i in range (10,110,10):
    model=Ridge(i)
    model.fit(X_train,Y_train)
    print(f"score for n estimators {i},{model.score(X_test,Y_test)}")

score for n estimators 10,0.5764371559180015
score for n estimators 20,0.5770381668560054
score for n estimators 30,0.577594957366619
score for n estimators 40,0.5781113028646223
score for n estimators 50,0.5785905898092147
score for n estimators 60,0.5790358623356866
score for n estimators 70,0.5794498625340332
score for n estimators 80,0.5798350653408457
score for n estimators 90,0.5801937088489765
score for n estimators 100,0.5805278207071454


In [100]:
from sklearn.ensemble import RandomForestRegressor
for i in range (10,110,10):
    model=RandomForestRegressor(n_estimators=i)
    model.fit(X_train,Y_train)
    print(f" score for {i} estimator is {model.score(X_test,Y_test)}")

 score for 10 estimator is 0.7869919586520553
 score for 20 estimator is 0.7953782504772979
 score for 30 estimator is 0.8022716438376327
 score for 40 estimator is 0.8028175477704369
 score for 50 estimator is 0.8022269411491246
 score for 60 estimator is 0.8027083666917649
 score for 70 estimator is 0.8065930974766224
 score for 80 estimator is 0.8061236679512781
 score for 90 estimator is 0.8060980171699111
 score for 100 estimator is 0.8080315405676122


In [101]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [102]:
heart_diss=pd.read_csv("heart-disease.csv")
heart_diss.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [103]:
heart_diss.isna().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [104]:
# Split the data 
X=heart_diss.drop("target",axis=1)
Y=heart_diss["target"]

In [105]:
np.random.seed(42)

from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2)


In [106]:
from sklearn.ensemble import RandomForestRegressor
np.random.seed(42)
for i in range (10,110,10):
    model=RandomForestRegressor(n_estimators=i)

    model.fit(X_train,Y_train)
    print(f"score for {i} estimator is: {model.score(X_test,Y_test)}")

score for 10 estimator is: 0.4721659482758621
score for 20 estimator is: 0.5262311422413792
score for 30 estimator is: 0.5601748084291188
score for 40 estimator is: 0.49139278017241395
score for 50 estimator is: 0.5104224137931035
score for 60 estimator is: 0.5143079501915709
score for 70 estimator is: 0.5063469827586208
score for 80 estimator is: 0.5593440193965518
score for 90 estimator is: 0.5041558908045978
score for 100 estimator is: 0.5122169181034484


## Regression Model evaluation metrics
1.R^2 pronounced
2.Mean squared error
3.Mean absolute error

In [107]:
X=housing_data.drop("target",axis=1)
Y=housing_data["target"]

In [108]:
#R*2 pronounced model
from sklearn.ensemble import RandomForestRegressor
model=RandomForestRegressor()

np.random.seed(42)

from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2)

model.fit(X_train,Y_train)
model.score(X_test,Y_test)

0.8065734772187598

In [109]:
Y_test

20046    0.47700
3024     0.45800
15663    5.00001
20484    2.18600
9814     2.78000
          ...   
15362    2.63300
16623    2.66800
18086    5.00001
2144     0.72300
3665     1.51500
Name: target, Length: 4128, dtype: float64

In [110]:
Y_test.mean()

2.0550030959302323

In [111]:
from sklearn.metrics import r2_score

y_preds_mean=np.full(len(Y_test),Y_test.mean())
y_preds_mean

array([2.0550031, 2.0550031, 2.0550031, ..., 2.0550031, 2.0550031,
       2.0550031])

In [112]:
r2_score(y_true=Y_test,y_pred=y_preds_mean)

0.0

**Mean Absolute Error**

In [113]:
from sklearn.metrics import mean_absolute_error
y_pred=model.predict(X_test)
mae=mean_absolute_error(Y_test,y_pred)
mae

0.32659871732073664

In [114]:
df=pd.DataFrame(data={"Actual Value":Y_test,"Predicted Value":y_pred})
df["difference"]=df["Predicted Value"]-df["Actual Value"]
df

Actual Value  Predicted Value  difference
20046       0.47700         0.493840    0.016840
3024        0.45800         0.754940    0.296940
15663       5.00001         4.928596   -0.071414
20484       2.18600         2.543160    0.357160
9814        2.78000         2.331760   -0.448240
...             ...              ...         ...
15362       2.63300         2.220380   -0.412620
16623       2.66800         1.947760   -0.720240
18086       5.00001         4.836378   -0.163632
2144        0.72300         0.717820   -0.005180
3665        1.51500         1.679010    0.164010

[4128 rows x 3 columns]

In [115]:
df["difference"].mean()

0.012048392126937589

In [116]:
np.abs(df["difference"]).mean()

0.32659871732073664

**Mean Square Error**

In [117]:
from sklearn.metrics import mean_squared_error
mean_squared_error(Y_test,y_pred)

0.2534678520824551

## Scoring methods for the evaluation of the model

In [118]:
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestRegressor

np.random.seed(42)

X=housing_data.drop("target",axis=1)
y=housing_data["target"]

model= RandomForestRegressor()

cv_acc=cross_val_score(model,X,y,cv=5)

cv_acc


array([0.51682388, 0.70279716, 0.74197717, 0.61638204, 0.68243183])

In [119]:
np.mean(cv_acc)

0.6520824166120266

In [120]:

cv_acc=cross_val_score(model,X,y,cv=5,scoring="neg_mean_absolute_error")
cv_acc

array([-0.53895506, -0.4118183 , -0.43888317, -0.464205  , -0.47454934])

In [121]:
np.abs(np.mean(cv_acc))

0.4656821754069768

### Now we are going to make evaluation of model using metrics 

In [122]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
%matplotlib inline

In [123]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error

X=housing_data.drop("target",axis=1)
y=housing_data["target"]

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

np.random.seed(42)

model=RandomForestRegressor(n_estimators=100)

model.fit(X_train,y_train)

model.score(X_test,y_test)

y_preds=model.predict(X_test)

In [124]:
Rscore=r2_score(y_test,y_preds)
print(f"The R^2 score of the model is {Rscore}")

The R^2 score of the model is 0.8075979966441083


In [125]:
MAE=mean_absolute_error(y_test,y_preds)
print(f"The mean absolute error of the model is {MAE}")

The mean absolute error of the model is 0.3312435266957366


In [126]:
MSE=mean_squared_error(y_test,y_preds)
print(f"The mean squared error of the model is {MSE}")

The mean squared error of the model is 0.2665635325812921


In [139]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

np.random.seed(42)

data=pd.read_csv("car-sales-extended-missing-data.csv")
# data.isna().sum()
# data.info()

data.dropna(subset=["Price"],inplace=True)

categorical_feature=["Make","Colour"]
categorical_transformer=Pipeline(steps=[
                                ("imputer",SimpleImputer(strategy="constant",fill_value="missing")),
                                ("onehot",OneHotEncoder(handle_unknown="ignore")) ])

door_feature=["Doors"]
door_transformer=Pipeline(steps=[
                            ("imputer",SimpleImputer(strategy="constant",fill_value=4)) ])

odometer_feature=["Odometer (KM)"]
ododmeter_transformer=Pipeline(steps=[
                                ("imputer",SimpleImputer(strategy="mean")) ])

preprocessor=ColumnTransformer(
                    transformers=(
                        ("cat",categorical_transformer,categorical_feature),
                        ("door",door_transformer,door_feature),
                        ("num",ododmeter_transformer,odometer_feature)
                        ))

model=Pipeline(steps=[("preprocessor",preprocessor),
                       ("model",RandomForestRegressor())
                     ])

X=data.drop("Price",axis=1)
y=data["Price"]

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

model.fit(X_train,y_train)
model.score(X_test,y_test)

0.22188417408787875

In [133]:
data

Make Colour  Odometer (KM)  Doors    Price
0     Honda  White        35431.0    4.0  15323.0
1       BMW   Blue       192714.0    5.0  19943.0
2     Honda  White        84714.0    4.0  28343.0
3    Toyota  White       154365.0    4.0  13434.0
4    Nissan   Blue       181577.0    3.0  14043.0
..      ...    ...            ...    ...      ...
995  Toyota  Black        35820.0    4.0  32042.0
996     NaN  White       155144.0    3.0   5716.0
997  Nissan   Blue        66604.0    4.0  31570.0
998   Honda  White       215883.0    4.0   4001.0
999  Toyota   Blue       248360.0    4.0  12732.0

[950 rows x 5 columns]