## Introduction

In [4]:
import numpy as np

In [5]:
a1=np.array([2,3,4,5,6])

In [6]:
a1

array([2, 3, 4, 5, 6])

In [7]:
a2=np.array([[1,23,4],[3,4,5]])
a2

array([[ 1, 23,  4],
       [ 3,  4,  5]])

In [8]:
a3=np.array([[[1,2,3],
              [4,5,6],
              [7,8,9]],
             [[10,11,12],
              [13,14,15],
              [16,17,18]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [9]:
a1.dtype

dtype('int32')

In [10]:
a2.dtype

dtype('int32')

In [11]:
a3.dtype

dtype('int32')

In [12]:
a1.shape,a2.shape,a3.shape

((5,), (2, 3), (2, 3, 3))

In [13]:
type(a1),type(a2),type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [14]:
a1.ndim,a2.ndim,a3.ndim

(1, 2, 3)

In [15]:
a1.size,a2.size,a3.size

(5, 6, 18)

In [16]:
import pandas as pd 

In [17]:
df=pd.DataFrame(a2,index=("a","b"))
df

0   1  2
a  1  23  4
b  3   4  5

## Creating a NumPy Array

In [18]:
sample_array=np.array([1,5,6,8])
sample_array

array([1, 5, 6, 8])

In [19]:
ones_array=np.ones((2,4))
ones_array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
ones_array.shape

(2, 4)

In [21]:
a1=np.arange(0,10)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
a2=np.arange(0,10,3)
a2

array([0, 3, 6, 9])

In [23]:
a3=np.random.randint(2,15,10)
a3

array([14,  6, 12, 11,  3, 10,  2, 10, 11,  2])

In [24]:
a4=np.random.rand(1,5)
a4

array([[0.11381078, 0.5100682 , 0.59632568, 0.50664283, 0.77555884]])

In [25]:
np.random.seed(0)
a5=np.random.random(size=(4,5))
a5

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ],
       [0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152],
       [0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606],
       [0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215]])

## Viewing Array and Matries

In [26]:
ar=np.random.randint(0,15,size=(2,3,4,5))
ar

array([[[[ 2,  3,  8,  1,  3],
         [13,  3,  3, 14,  7],
         [ 0,  1,  9,  9,  0],
         [10,  4,  7,  3, 14]],

        [[11,  2,  7, 12,  2],
         [ 0,  0,  4,  5,  5],
         [ 6,  8,  4,  1,  4],
         [ 9, 10, 10,  8,  1]],

        [[ 1,  7,  9,  9,  3],
         [ 6,  7, 11, 14,  2],
         [11,  0, 14,  3,  5],
         [12,  9, 10,  4, 11]]],


       [[[ 4,  6,  4,  4,  3],
         [12,  4,  4,  8, 14],
         [ 4,  3, 10,  7, 13],
         [ 5,  5,  0,  1,  5]],

        [[ 9,  3,  0,  5, 14],
         [ 0,  1,  2,  4,  2],
         [ 0, 13,  3,  2, 10],
         [13,  0,  7,  5,  9]],

        [[ 0, 10,  2, 11, 10],
         [ 7, 11,  2,  9,  2],
         [14,  3, 14, 11,  3],
         [ 2, 14,  3,  4,  1]]]])

In [27]:
ar[:,:,:,]

array([[[[ 2,  3,  8,  1,  3],
         [13,  3,  3, 14,  7],
         [ 0,  1,  9,  9,  0],
         [10,  4,  7,  3, 14]],

        [[11,  2,  7, 12,  2],
         [ 0,  0,  4,  5,  5],
         [ 6,  8,  4,  1,  4],
         [ 9, 10, 10,  8,  1]],

        [[ 1,  7,  9,  9,  3],
         [ 6,  7, 11, 14,  2],
         [11,  0, 14,  3,  5],
         [12,  9, 10,  4, 11]]],


       [[[ 4,  6,  4,  4,  3],
         [12,  4,  4,  8, 14],
         [ 4,  3, 10,  7, 13],
         [ 5,  5,  0,  1,  5]],

        [[ 9,  3,  0,  5, 14],
         [ 0,  1,  2,  4,  2],
         [ 0, 13,  3,  2, 10],
         [13,  0,  7,  5,  9]],

        [[ 0, 10,  2, 11, 10],
         [ 7, 11,  2,  9,  2],
         [14,  3, 14, 11,  3],
         [ 2, 14,  3,  4,  1]]]])

## Airthmetic operation on array

In [28]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
a2

array([0, 3, 6, 9])

In [30]:
a3

array([14,  6, 12, 11,  3, 10,  2, 10, 11,  2])

In [31]:
a4

array([[0.11381078, 0.5100682 , 0.59632568, 0.50664283, 0.77555884]])

In [32]:
a1*5

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [33]:
a1/2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [34]:
array=np.array([1,9,7,3,12])

In [35]:
a1+array

ValueError: operands could not be broadcast together with shapes (10,) (5,) 

In [36]:
a1*array

ValueError: operands could not be broadcast together with shapes (10,) (5,) 

In [37]:
a1*a2

ValueError: operands could not be broadcast together with shapes (10,) (4,) 

In [38]:
a1=np.array([1,2,6,4,7,8])

In [39]:
a1=a1.reshape(2,3)

In [40]:
a1*a2

ValueError: operands could not be broadcast together with shapes (2,3) (4,) 

## Aggregation
making things into cluster


In [41]:
lis1=[1,24,67,8,8]

In [ ]:
sum(lis1)

In [ ]:
a=np.random.random(10)
a

In [ ]:
#There is a difference in the sum of python ((sum())) and numpy sums i.e np.sum()
%timeit sum(a)
%timeit np.sum(a)

In [ ]:
np.mean(a1)

In [ ]:
np.max(a2)

In [ ]:
np.min(a2)

In [ ]:
np.std(a2)

In [ ]:
np.var(a2)

## Standard Deviation and Variance

In [ ]:
high_arr=np.array([1,10,100,200,4000,5000])
low_array=np.array([2,4,6,8])

In [ ]:
np.var(high_arr)

In [ ]:
np.var(low_array)

In [ ]:
np.std(high_arr)

In [ ]:
np.sqrt(np.var(high_arr))

##  Butter sales stock report

In [ ]:
butter_sales=np.random.randint(10,size=(5,3))
butter_sales

In [ ]:
import pandas as pd
sales=pd.DataFrame(butter_sales,index=["Mon","Tues","Wed","Thu","Fri"],
                         columns=("Almond Butter","Peanut Butter","Cashew Butter"))
sales

In [ ]:
price=np.array([10,9,12])


In [ ]:
Butter_prices=pd.DataFrame(price.reshape(1,3),index=["Price"],columns=("Almond Butter","Peanut Butter","Cashew Butter"))
Butter_prices

In [ ]:
total=butter_sales.dot(price)
total

In [ ]:
sales.shape,Butter_prices.shape

In [ ]:
daily_sales=sales.dot(Butter_prices.T)
daily_sales

In [ ]:
sales["Total ($)"]=daily_sales
sales

##  Image Processing using NumPy

import pandas as pd
< img src="logo.png"/>


In [51]:
import pandas as pd 

<img src = "Images/photo personal.jpg"/>

SyntaxError: invalid syntax (2250491678.py, line 3)