# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np


In [2]:
# Create a 1-dimensional NumPy array using np.array()
a1=np.array([1,2,3,4,5])


# Create a 2-dimensional NumPy array using np.array()
a2=np.array([[1,2,3],[4,5,6]])

# Create a 3-dimensional Numpy array using np.array()
a3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [3]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.ndim,a2.ndim,a3.ndim
a1.dtype,a2.dtype,a3.dtype
a1.size,a2.size,a3.size
type(a1),type(a2),type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [4]:
# Attributes of 2-dimensional array
a2
a3
a1

array([1, 2, 3, 4, 5])

In [14]:
# Attributes of 3-dimensional array
a3.shape

(1, 3, 3)

In [5]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd 
data_frame=pd.DataFrame(a2)
data_frame

0  1  2
0  1  2  3
1  4  5  6

In [6]:
# Create an array of shape (10, 2) with only ones
ones_array=np.ones((4,5))
ones_array

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
# Create an array of shape (7, 2, 3) of only zeros
array_zeros=np.zeros((7,2,3))
array_zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [7]:
# Create an array within a range of 0 and 100 with step 3
arr=np.arange(0,100,3)
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [8]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
ar1=np.random.randint(0,10,size=(7,2))
ar1

array([[1, 3],
       [9, 1],
       [5, 1],
       [8, 1],
       [8, 1],
       [2, 2],
       [0, 4]])

In [9]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
ar2=np.random.random(size=(3,5))
ar2

array([[0.62197809, 0.15562396, 0.00343565, 0.20532414, 0.92509645],
       [0.72150559, 0.31973297, 0.27754511, 0.64582561, 0.01636136],
       [0.98818918, 0.13055701, 0.68026505, 0.11615656, 0.92334458]])

In [10]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
arr=np.random.randint(0,10,size=(4,6))
arr

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [11]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
array=np.random.randint(1,10,size=(3,7))
array
# Find the unique numbers in the array you just created
np.unique(array)

array([1, 2, 3, 4, 5, 7, 9])

In [12]:
# Find the 0'th index of the latest array you created
array[0]

array([9, 1, 3, 7, 4, 9, 3])

In [13]:
# Get the first 2 rows of latest array you created
array[:2]

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2]])

In [14]:
# Get the first 2 values of the first 2 rows of the latest array
array[:2,:1]

array([[9],
       [5]])

In [15]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
arr1=np.random.randint(0,10,size=(3,5))
ones_arr=np.ones((3,5))
ones_arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
# Add the two arrays together
arr1+ones_arr

array([[ 7.,  8.,  3.,  1.,  4.],
       [ 2.,  8.,  4.,  2.,  6.],
       [ 6., 10.,  4.,  6.,  2.]])

In [17]:
# Create another array of ones of shape (5, 3)
a1=np.ones((5,3))
a1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
# Try add the array of ones and the other most recent array together
arr1+a1.T

array([[ 7.,  8.,  3.,  1.,  4.],
       [ 2.,  8.,  4.,  2.,  6.],
       [ 6., 10.,  4.,  6.,  2.]])

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [19]:
# Create another array of ones of shape (3, 5)
a2=np.ones((3,5))
a2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
# Subtract the new array of ones from the other most recent array
arr1-a2

array([[ 5.,  6.,  1., -1.,  2.],
       [ 0.,  6.,  2.,  0.,  4.],
       [ 4.,  8.,  2.,  4.,  0.]])

In [21]:
# Multiply the ones array with the latest array
arr1*a2

array([[6., 7., 2., 0., 3.],
       [1., 7., 3., 1., 5.],
       [5., 9., 3., 5., 1.]])

In [22]:
# Take the latest array to the power of 2 using '**'
arr1**2

array([[36, 49,  4,  0,  9],
       [ 1, 49,  9,  1, 25],
       [25, 81,  9, 25,  1]])

In [23]:
# Do the same thing with np.square()
np.square(arr1)

array([[36, 49,  4,  0,  9],
       [ 1, 49,  9,  1, 25],
       [25, 81,  9, 25,  1]])

In [24]:
# Find the mean of the latest array using np.mean()
arr1.mean()

3.8666666666666667

In [25]:
# Find the maximum of the latest array using np.max()
arr1.max()

9

In [26]:
# Find the minimum of the latest array using np.min()
np.min(arr1)

0

In [27]:
# Find the standard deviation of the latest array
arr1.std()

2.578543947441829

In [28]:
# Find the variance of the latest array
arr1.var()

6.648888888888889

In [29]:
# Reshape the latest array to (3, 5, 1)
arr1.reshape(3,5,1)

array([[[6],
        [7],
        [2],
        [0],
        [3]],

       [[1],
        [7],
        [3],
        [1],
        [5]],

       [[5],
        [9],
        [3],
        [5],
        [1]]])

In [30]:
# Transpose the latest array
arr1.T

array([[6, 1, 5],
       [7, 7, 9],
       [2, 3, 3],
       [0, 1, 5],
       [3, 5, 1]])

What does the transpose do?

In [31]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
ar1=np.random.randint(0,10,size=(3,3))
ar2=np.random.randint(0,10,size=(3,2))
ar1,ar2

(array([[9, 1, 9],
        [3, 7, 6],
        [8, 7, 4]]),
 array([[1, 4],
        [7, 9],
        [8, 8]]))

In [34]:
# Perform a dot product on the two newest arrays you created
result=ar1.dot(ar2)
result

array([[ 88, 117],
       [100, 123],
       [ 89, 127]])

In [36]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
a1=np.random.randint(0,10,size=(4,3))
a2=np.random.randint(0,10,size=(4,3))
a1,a2

(array([[0, 8, 6],
        [8, 7, 0],
        [7, 7, 2],
        [0, 7, 2]]),
 array([[2, 0, 4],
        [9, 6, 9],
        [8, 6, 8],
        [7, 1, 0]]))

In [37]:
# Perform a dot product on the two newest arrays you created
a1.dot(a2)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [39]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product n them both
a1.dot(a2.T)

array([[ 24, 102,  96,   8],
       [ 16, 114, 106,  63],
       [ 22, 123, 114,  56],
       [  8,  60,  58,   7]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [40]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
a3=np.random.randint(0,10,size=(3,5))
a4=np.random.randint(0,10,size=(3,5))

a3,a4

(array([[6, 6, 7, 4, 2],
        [7, 5, 2, 0, 2],
        [4, 2, 0, 4, 9]]),
 array([[6, 6, 8, 9, 9],
        [2, 6, 0, 3, 3],
        [4, 6, 6, 3, 6]]))

In [41]:
# Compare the two arrays with '>'
a3>a4

array([[False, False, False, False, False],
       [ True, False,  True, False, False],
       [False, False, False,  True,  True]])

What happens when you compare the arrays with `>`?

In [42]:
# Compare the two arrays with '>='
a3>=a4

array([[ True,  True, False, False, False],
       [ True, False,  True, False, False],
       [ True, False, False,  True,  True]])

In [43]:
# Find which elements of the first array are greater than 7
a1>7

array([[False,  True, False],
       [ True, False, False],
       [False, False, False],
       [False, False, False]])

In [44]:
# Which parts of each array are equal? (try using '==')
a3==a4

array([[ True,  True, False, False, False],
       [False, False, False, False, False],
       [ True, False, False, False, False]])

In [51]:
# Sort one of the arrays you just created in ascending order
a4
a4.sort()
a4

array([[6, 6, 8, 9, 9],
       [0, 2, 3, 3, 6],
       [3, 4, 6, 6, 6]])

In [67]:
np.argsort(a4)

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]], dtype=int64)

In [70]:
np.argmax(a4,axis=1)

array([4, 2, 3], dtype=int64)

In [66]:
# Sort the indexes of one of the arrays you just created
# np.argsort(a4,axis=0)
a4

array([[0, 2, 3, 3, 6],
       [3, 4, 6, 6, 6],
       [6, 6, 8, 9, 9]])

In [54]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(a4)

13

In [71]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(a4)

0

In [55]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.max(a4,axis=1)

array([6, 6, 9])

In [56]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.min(a4,axis=0)

array([0, 2, 3, 3, 6])

In [60]:
# Create an array of normally distributed random numbers
a5=np.random.normal(size=(2,4))
a5

array([[ 0.29612028,  0.26105527,  0.00511346, -0.23458713],
       [-1.41537074, -0.42064532, -0.34271452, -0.80227727]])

In [64]:
# Create an array with 10 evenly spaced numbers between 1 and 100
a=np.arange(1,100,10)
a

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.